### PR TITLE
feat: receive unitId as prop and forward to learning-assistant backend

### PR DESCRIPTION
**Pull request by MichaelRoytman**
### Description

**Jira**: [COSMO-75](https://2u-internal.atlassian.net/browse/COSMO-75)

This commit modifies the `Xpert` components to accept a new `unitId` prop, which presents the unit usage key in which the `Xpert` is being rendered. This unit ID is forwarded to the chat completion backend API.

### CODE REVIEW

**Review by alangsto — APPROVED** [review]
This looks good to me, but I do wonder if it would be better to use React context as opposed to passing the props all the way down. I don't know if context is overkill, but just wanted to throw it out there as an idea.

**Comment by MichaelRoytman** [comment]
> This looks good to me, but I do wonder if it would be better to use React context as opposed to passing the props all the way down. I don't know if context is overkill, but just wanted to throw it out there as an idea.

I think that's a good point. I actively didn't like all of this prop drilling as I was doing it but also didn't really want to deal with setting up the context. I'll take a look at the context API and re-familiarize myself with it to see if that's something I could do. I think that would definitely be an improvement.

**Comment by MichaelRoytman** [comment]
@alangsto Hey, Alie. Following up on your feedback to use context, I did some reading. I feel like using React context isn't justified because we’re only passing the state through a few levels, and that’s considered normal and expected; [here's a link to the React docs](https://react.dev/learn/passing-data-deeply-with-context#before-you-use-context) that explain this rationale in more detail.

I did do some refactoring based on the `Extract components and pass JSX as children to them` section to remove one level of prop-passing, but I think it would be best to avoid context.

Let me know what you think.

**Review by alangsto — APPROVED** [review]
This looks good! I appreciate you taking the time to look into using context, and this looks like the right approach.

**Pull request merged**
